development:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_development
  pool: 5
  username: scardinho
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_test
  pool: 5
  username: scardinho
  password: 